name: Rutina Diaria F1 Bot Modular

on:
  schedule:
    # Se ejecuta a las 01:20, 08:20, 10:20, 12:20 y 20:20 UTC
    - cron: '20 1,8,10,12,20 * * *' 
  workflow_dispatch: 

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar código
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar dependencias

        run: |
          pip install gspread requests beautifulsoup4 pandas gspread-dataframe oauth2client lxml

      - name: ▶️ Ejecutar Bot (main.py)
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
   
        run: python main.py
